project:
  type: default
  pre-render:
    - vault-sync-bib

  render:
    - "drafts/**/*.qmd"
    - "drafts/**/*.md"
    - "notes/**/*.md"

execute:
  freeze: auto

from: markdown+wikilinks_title_after_pipe+mark
filters:
  - at: pre-ast
    path: _extensions/obsidian/obsidian.lua

format:
  html:
    toc: true
    code-fold: true
    highlight-style: github-dark
  typst:
    papersize: us-letter
    number-sections: true
  pdf:
    documentclass: article
    papersize: letter
    geometry:
      - margin=1in
    number-sections: true
    colorlinks: true
    keep-tex: true

bibliography:
  - references.bib
  - library.bib
