# bash/zsh git prompt support
#
# Copyright (C) 2006,2007 Shawn O. Pearce <spearce@spearce.org>
# Distributed under the GNU General Public License, version 2.0.
#
# This script allows you to see repository status in your prompt.
#
# To enable:
#
#    1) Copy this file to somewhere (e.g. ~/.git-prompt.sh).
#    2) Add the following line to your .bashrc/.zshrc:
#        source ~/.git-prompt.sh
#    3a) Change your PS1 to call __git_ps1 as
#        command-substitution:
#        Bash: PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
#        ZSH:  setopt PROMPT_SUBST ; PS1='[%n@%m %c$(__git_ps1 " (%s)")]\$ '
#        the optional argument will be used as format string.
#    3b) Alternatively, for a slightly faster prompt, __git_ps1 can
#        be used for PROMPT_COMMAND in Bash or for precmd() in Zsh
#        with two parameters, <pre> and <post>, which are strings
#        you would put in $PS1 before and after the status string
#        generated by the git-prompt machinery.  e.g.
#        Bash: PROMPT_COMMAND='__git_ps1 "\u@\h:\w" "\\\$ "'
#          will show username, at-sign, host, colon, cwd, then
#          various status string, followed by dollar and SP, as
#          your prompt.
#        ZSH:  precmd () { __git_ps1 "%n" ":%~$ " "|%s" }
#          will show username, pipe, then various status string,
#          followed by colon, cwd, dollar and SP, as your prompt.
#        Optionally, you can supply a third argument with a printf
#        format string to finetune the output of the branch status
#
# The repository status will be displayed only if you are currently in a
# git repository. The %s token is the placeholder for the shown status.
#
# The prompt status always includes the current branch name.
#
# In addition, if you set GIT_PS1_SHOWDIRTYSTATE to a nonempty value,
# unstaged (*) and staged (+) changes will be shown next to the branch
# name.  You can configure this per-repository with the
# bash.showDirtyState variable, which defaults to true once
# GIT_PS1_SHOWDIRTYSTATE is enabled.
#
# You can also see if currently something is stashed, by setting
# GIT_PS1_SHOWSTASHSTATE to a nonempty value. If something is stashed,
# then a '$' will be shown next to the branch name.
#
# If you would like to see if there're untracked files, then you can set
# GIT_PS1_SHOWUNTRACKEDFILES to a nonempty value. If there're untracked
# files, then a '%' will be shown next to the branch name.  You can
# configure this per-repository with the bash.showUntrackedFiles
# variable, which defaults to true once GIT_PS1_SHOWUNTRACKEDFILES is
# enabled.
#
# If you would like to see the difference between HEAD and its upstream,
# set GIT_PS1_SHOWUPSTREAM="auto".  A "<" indicates you are behind, ">"
# indicates you are ahead, "<>" indicates you have diverged and "="
# indicates that there is no difference. You can further control
# behaviour by setting GIT_PS1_SHOWUPSTREAM to a space-separated list
# of values:
#
#     verbose       show number of commits ahead/behind (+/-) upstream
#     name          if verbose, then also show the upstream abbrev name
#     legacy        don't use the '--count' option available in recent
#                   versions of git-rev-list
#     git           always compare HEAD to @{upstream}
#     svn           always compare HEAD to your SVN upstream
#
# You can change the separator between the branch name and the above
# state symbols by setting GIT_PS1_STATESEPARATOR. The default separator
# is SP.
#
# By default, __git_ps1 will compare HEAD to your SVN upstream if it can
# find one, or @{upstream} otherwise.  Once you have set
# GIT_PS1_SHOWUPSTREAM, you can override it on a per-repository basis by
# setting the bash.showUpstream config variable.
#
# If you would like to see more information about the identity of
# commits checked out as a detached HEAD, set GIT_PS1_DESCRIBE_STYLE
# to one of these values:
#
#     contains      relative to newer annotated tag (v1.6.3.2~35)
#     branch        relative to newer tag or branch (master~4)
#     describe      relative to older annotated tag (v1.6.3.1-13-gdd42c2f)
#     tag           relative to any older tag (v1.6.3.1-13-gdd42c2f)
#     default       exactly matching tag
#
# If you would like a colored hint about the current dirty state, set
# GIT_PS1_SHOWCOLORHINTS to a nonempty value. The colors are based on
# the colored output of "git status -sb" and are available only when
# using __git_ps1 for PROMPT_COMMAND or precmd.
#
# If you would like __git_ps1 to do nothing in the case when the current
# directory is set up to be ignored by git, then set
# GIT_PS1_HIDE_IF_PWD_IGNORED to a nonempty value. Override this on the
# repository level by setting bash.hideIfPwdIgnored to "false".

# check whether printf supports -v
__git_printf_supports_v=
printf -v __git_printf_supports_v -- '%s' yes >/dev/null 2>&1

# stores the divergence from upstream in $p
# used by GIT_PS1_SHOWUPSTREAM
__git_ps1_show_upstream ()
{
	local key value
	local svn_remote svn_url_pattern count n
	local upstream=git legacy="" verbose="" name=""

	svn_remote=()
	# get some config options from git-config
	local output="$(git config -z --get-regexp '^(svn-remote\..*\.url|bash\.showupstream)$' 2>/dev/null | tr '\0\n' '\n ')"
	while read -r key value; do
		case "$key" in
		bash.showupstream)
			GIT_PS1_SHOWUPSTREAM="$value"
			if [[ -z "${GIT_PS1_SHOWUPSTREAM}" ]]; then
				p=""
				return
			fi
			;;
		svn-remote.*.url)
			svn_remote[$((${#svn_remote[@]} + 1))]="$value"
			svn_url_pattern="$svn_url_pattern\\|$value"
			upstream=svn+git # default upstream is SVN if available, else git
			;;
		esac
	done <<< "$output"

	# parse configuration values
	for option in ${GIT_PS1_SHOWUPSTREAM}; do
		case "$option" in
		git|svn) upstream="$option" ;;
		verbose) verbose=1 ;;
		legacy)  legacy=1  ;;
		name)    name=1 ;;
		esac
	done

	# Find our upstream
	case "$upstream" in
	git)    upstream="@{upstream}" ;;
	svn*)
		# get the upstream from the "git-svn-id: ..." in a commit message
		# (git-svn uses essentially the same procedure internally)
		local -a svn_upstream
		svn_upstream=($(git log --first-parent -1 \
					--grep="^git-svn-id: \(${svn_url_pattern#??}\)" 2>/dev/null))
		if [[ 0 -ne ${#svn_upstream[@]} ]]; then
			svn_upstream=${svn_upstream[${#svn_upstream[@]} - 2]}
			svn_upstream=${svn_upstream%@*}
			local n_stop="${#svn_remote[@]}"
			for ((n=1; n <= n_stop; n++)); do
				svn_upstream=${svn_upstream#${svn_remote[$n]}}
			done

			if [[ -z "$svn_upstream" ]]; then
				# default branch name for checkouts with no layout:
				upstream=${GIT_SVN_ID:-git-svn}
			else
				upstream=${svn_upstream#/}
			fi
		elif [[ "svn+git" = "$upstream" ]]; then
			upstream="@{upstream}"
		fi
		;;
	esac

	# Find how many commits we are ahead/behind our upstream
	if [[ -z "$legacy" ]]; then
		count="$(git rev-list --count --left-right \
				"$upstream"...HEAD 2>/dev/null)"
	else
		# produce equivalent output to --count for older versions of git
		local commits
		if commits="$(git rev-list --left-right "$upstream"...HEAD 2>/dev/null)"
		then
			local commit behind=0 ahead=0
			for commit in $commits
			do
				case "$commit" in
				"<"*) ((behind++)) ;;
				*)    ((ahead++))  ;;
				esac
			done
			count="$behind	$ahead"
		else
			count=""
		fi
	fi

	# calculate the result
	if [[ -z "$verbose" ]]; then
		case "$count" in
		"") # no upstream
			p="" ;;
		"0	0") # equal to upstream
			p="=" ;;
		"0	"*) # ahead of upstream
			p=">" ;;
		*"	0") # behind upstream
			p="<" ;;
		*)	    # diverged from upstream
			p="<>" ;;
		esac
	else
		case "$count" in
		"") # no upstream
			p="" ;;
		"0	0") # equal to upstream
			p=" u=" ;;
		"0	"*) # ahead of upstream
			p=" u+${count#0	}" ;;
		*"	0") # behind upstream
			p=" u-${count%	0}" ;;
		*)	    # diverged from upstream
			p=" u+${count#*	}-${count%	*}" ;;
		esac
		if [[ -n "$count" && -n "$name" ]]; then
			__git_ps1_upstream_name=$(git rev-parse \
				--abbrev-ref "$upstream" 2>/dev/null)
			if [ $pcmode = yes ] && [ $ps1_expanded = yes ]; then
				p="$p \${__git_ps1_upstream_name}"
			else
				p="$p ${__git_ps1_upstream_name}"
				# not needed anymore; keep user's
				# environment clean
				unset __git_ps1_upstream_name
			fi
		fi
	fi

}

# Helper function that is meant to be called from __git_ps1.  It
# injects color codes into the appropriate gitstring variables used
# to build a gitstring.
__git_ps1_colorize_gitstring ()
{
	if [[ -n ${ZSH_VERSION-} ]]; then
		local c_red='%F{red}'
		local c_green='%F{green}'
		local c_lblue='%F{blue}'
		local c_clear='%f'
	else
		# Using \[ and \] around colors is necessary to prevent
		# issues with command line editing/browsing/completion!
		local c_red='\[\e[31m\]'
		local c_green='\[\e[32m\]'
		local c_lblue='\[\e[1;34m\]'
		local c_clear='\[\e[0m\]'
	fi
	local bad_color=$c_red
	local ok_color=$c_green
	local flags_color="$c_lblue"

	local branch_color=""
	if [ $detached = no ]; then
		branch_color="$ok_color"
	else
		branch_color="$bad_color"
	fi
	c="$branch_color$c"

	z="$c_clear$z"
	if [ "$w" = "*" ]; then
		w="$bad_color$w"
	fi
	if [ -n "$i" ]; then
		i="$ok_color$i"
	fi
	if [ -n "$s" ]; then
		s="$flags_color$s"
	fi
	if [ -n "$u" ]; then
		u="$bad_color$u"
	fi
	r="$c_clear$r"
}

# Helper function to read the first line of a file into a variable.
# __git_eread requires 2 arguments, the file path and the name of the
# variable, in that order.
__git_eread ()
{
	test -r "$1" && IFS=$'\r\n' read "$2" <"$1"
}

# see if a cherry-pick or revert is in progress, if the user has committed a
# conflict resolution with 'git commit' in the middle of a sequence of picks or
# reverts then CHERRY_PICK_HEAD/REVERT_HEAD will not exist so we have to read
# the todo file.
__git_sequencer_status ()
{
	local todo
	if test -f "$g/CHERRY_PICK_HEAD"
	then
		r="|CHERRY-PICKING"
		return 0;
	elif test -f "$g/REVERT_HEAD"
	then
		r="|REVERTING"
		return 0;
	elif __git_eread "$g/sequencer/todo" todo
	then
		case "$todo" in
		p[\ \	]|pick[\ \	]*)
			r="|CHERRY-PICKING"
			return 0
		;;
		revert[\ \	]*)
			r="|REVERTING"
			return 0
		;;
		esac
	fi
	return 1
}

# __git_ps1 accepts 0 or 1 arguments (i.e., format string)
# when called from PS1 using command substitution
# in this mode it prints text to add to bash PS1 prompt (includes branch name)
#
# __git_ps1 requires 2 or 3 arguments when called from PROMPT_COMMAND (pc)
# in that case it _sets_ PS1. The arguments are parts of a PS1 string.
# when two arguments are given, the first is prepended and the second appended
# to the state string when assigned to PS1.
# The optional third parameter will be used as printf format string to further
# customize the output of the git-status string.
# In this mode you can request colored hints using GIT_PS1_SHOWCOLORHINTS=true
__git_ps1 ()
{
	# preserve exit status
	local exit=$?
	local pcmode=no
	local detached=no
	local ps1pc_start='\u@\h:\w '
	local ps1pc_end='\$ '
	local printf_format=' (%s)'

	case "$#" in
		2|3)	pcmode=yes
			ps1pc_start="$1"
			ps1pc_end="$2"
			printf_format="${3:-$printf_format}"
			# set PS1 to a plain prompt so that we can
			# simply return early if the prompt should not
			# be decorated
			PS1="$ps1pc_start$ps1pc_end"
		;;
		0|1)	printf_format="${1:-$printf_format}"
		;;
		*)	return $exit
		;;
	esac

	# ps1_expanded:  This variable is set to 'yes' if the shell
	# subjects the value of PS1 to parameter expansion:
	#
	#   * bash does unless the promptvars option is disabled
	#   * zsh does not unless the PROMPT_SUBST option is set
	#   * POSIX shells always do
	#
	# If the shell would expand the contents of PS1 when drawing
	# the prompt, a raw ref name must not be included in PS1.
	# This protects the user from arbitrary code execution via
	# specially crafted ref names.  For example, a ref named
	# 'refs/heads/$(IFS=_;cmd=sudo_rm_-rf_/;$cmd)' might cause the
	# shell to execute 'sudo rm -rf /' when the prompt is drawn.
	#
	# Instead, the ref name should be placed in a separate global
	# variable (in the __git_ps1_* namespace to avoid colliding
	# with the user's environment) and that variable should be
	# referenced from PS1.  For example:
	#
	#     __git_ps1_foo=$(do_something_to_get_ref_name)
	#     PS1="...stuff...\${__git_ps1_foo}...stuff..."
	#
	# If the shell does not expand the contents of PS1, the raw
	# ref name must be included in PS1.
	#
	# The value of this variable is only relevant when in pcmode.
	#
	# Assume that the shell follows the POSIX specification and
	# expands PS1 unless determined otherwise.  (This is more
	# likely to be correct if the user has a non-bash, non-zsh
	# shell and safer than the alternative if the assumption is
	# incorrect.)
	#
	local ps1_expanded=yes
	[ -z "${ZSH_VERSION-}" ] || [[ -o PROMPT_SUBST ]] || ps1_expanded=no
	[ -z "${BASH_VERSION-}" ] || shopt -q promptvars || ps1_expanded=no

	local repo_info rev_parse_exit_code
	repo_info="$(git rev-parse --git-dir --is-inside-git-dir \
		--is-bare-repository --is-inside-work-tree \
		--short HEAD 2>/dev/null)"
	rev_parse_exit_code="$?"

	if [ -z "$repo_info" ]; then
		return $exit
	fi

	local short_sha=""
	if [ "$rev_parse_exit_code" = "0" ]; then
		short_sha="${repo_info##*$'\n'}"
		repo_info="${repo_info%$'\n'*}"
	fi
	local inside_worktree="${repo_info##*$'\n'}"
	repo_info="${repo_info%$'\n'*}"
	local bare_repo="${repo_info##*$'\n'}"
	repo_info="${repo_info%$'\n'*}"
	local inside_gitdir="${repo_info##*$'\n'}"
	local g="${repo_info%$'\n'*}"

	if [ "true" = "$inside_worktree" ] &&
	   [ -n "${GIT_PS1_HIDE_IF_PWD_IGNORED-}" ] &&
	   [ "$(git config --bool bash.hideIfPwdIgnored)" != "false" ] &&
	   git check-ignore -q .
	then
		return $exit
	fi

	local r=""
	local b=""
	local step=""
	local total=""
	if [ -d "$g/rebase-merge" ]; then
		__git_eread "$g/rebase-merge/head-name" b
		__git_eread "$g/rebase-merge/msgnum" step
		__git_eread "$g/rebase-merge/end" total
		if [ -f "$g/rebase-merge/interactive" ]; then
			r="|REBASE-i"
		else
			r="|REBASE-m"
		fi
	else
		if [ -d "$g/rebase-apply" ]; then
			__git_eread "$g/rebase-apply/next" step
			__git_eread "$g/rebase-apply/last" total
			if [ -f "$g/rebase-apply/rebasing" ]; then
				__git_eread "$g/rebase-apply/head-name" b
				r="|REBASE"
			elif [ -f "$g/rebase-apply/applying" ]; then
				r="|AM"
			else
				r="|AM/REBASE"
			fi
		elif [ -f "$g/MERGE_HEAD" ]; then
			r="|MERGING"
		elif __git_sequencer_status; then
			:
		elif [ -f "$g/BISECT_LOG" ]; then
			r="|BISECTING"
		fi

		if [ -n "$b" ]; then
			:
		elif [ -h "$g/HEAD" ]; then
			# symlink symbolic ref
			b="$(git symbolic-ref HEAD 2>/dev/null)"
		else
			local head=""
			if ! __git_eread "$g/HEAD" head; then
				return $exit
			fi
			# is it a symbolic ref?
			b="${head#ref: }"
			if [ "$head" = "$b" ]; then
				detached=yes
				b="$(
				case "${GIT_PS1_DESCRIBE_STYLE-}" in
				(contains)
					git describe --contains HEAD ;;
				(branch)
					git describe --contains --all HEAD ;;
				(tag)
					git describe --tags HEAD ;;
				(describe)
					git describe HEAD ;;
				(* | default)
					git describe --tags --exact-match HEAD ;;
				esac 2>/dev/null)" ||

				b="$short_sha..."
				b="($b)"
			fi
		fi
	fi

	if [ -n "$step" ] && [ -n "$total" ]; then
		r="$r $step/$total"
	fi

	local w=""
	local i=""
	local s=""
	local u=""
	local c=""
	local p=""

	if [ "true" = "$inside_gitdir" ]; then
		if [ "true" = "$bare_repo" ]; then
			c="BARE:"
		else
			b="GIT_DIR!"
		fi
	elif [ "true" = "$inside_worktree" ]; then
		if [ -n "${GIT_PS1_SHOWDIRTYSTATE-}" ] &&
		   [ "$(git config --bool bash.showDirtyState)" != "false" ]
		then
			git diff --no-ext-diff --quiet || w="*"
			git diff --no-ext-diff --cached --quiet || i="+"
			if [ -z "$short_sha" ] && [ -z "$i" ]; then
				i="#"
			fi
		fi
		if [ -n "${GIT_PS1_SHOWSTASHSTATE-}" ] &&
		   git rev-parse --verify --quiet refs/stash >/dev/null
		then
			s="$"
		fi

		if [ -n "${GIT_PS1_SHOWUNTRACKEDFILES-}" ] &&
		   [ "$(git config --bool bash.showUntrackedFiles)" != "false" ] &&
		   git ls-files --others --exclude-standard --directory --no-empty-directory --error-unmatch -- ':/*' >/dev/null 2>/dev/null
		then
			u="%${ZSH_VERSION+%}"
		fi

		if [ -n "${GIT_PS1_SHOWUPSTREAM-}" ]; then
			__git_ps1_show_upstream
		fi
	fi

	local z="${GIT_PS1_STATESEPARATOR-" "}"

	# NO color option unless in PROMPT_COMMAND mode
	if [ $pcmode = yes ] && [ -n "${GIT_PS1_SHOWCOLORHINTS-}" ]; then
		__git_ps1_colorize_gitstring
	fi

	b=${b##refs/heads/}
	if [ $pcmode = yes ] && [ $ps1_expanded = yes ]; then
		__git_ps1_branch_name=$b
		b="\${__git_ps1_branch_name}"
	fi

	local f="$w$i$s$u"
	local gitstring="$c$b${f:+$z$f}$r$p"

	if [ $pcmode = yes ]; then
		if [ "${__git_printf_supports_v-}" != yes ]; then
			gitstring=$(printf -- "$printf_format" "$gitstring")
		else
			printf -v gitstring -- "$printf_format" "$gitstring"
		fi
		PS1="$ps1pc_start$gitstring$ps1pc_end"
	else
		printf -- "$printf_format" "$gitstring"
	fi

	return $exit
}

# =============================================================================
# zfiles addition -- everything above this line is git's contrib/git-prompt.sh,
# verbatim. Keep local code below the line so refreshing the vendored copy is a
# matter of replacing everything above it.
# =============================================================================

# Which GitHub account applies *here*, for the prompt. Lives alongside
# __git_ps1 because it answers the same kind of question and both prompts
# (zsh prompt.sh, bash prompt.sh) want them together.
#
# The account is per-directory, not global: ~/.gitconfig carries more than one
# identity on the same host (a personal account and a work one) and selects
# between them with includeIf rules -- by path for anything under the work
# tree, by remote org otherwise. The included file sets `github.user` alongside
# the author fields and the SSH key, so asking git for that key gets the same
# answer git itself would use. No identity, path or org is spelled out in this
# file; it is all read back out of the git config, so a new tree or org needs
# only the ~/.gitconfig includeIf it would need anyway.
#
# Three layers, in order:
#   1. `git config --get github.user` -- the includeIf-resolved identity.
#   2. the same gitdir: rules applied to $PWD, for when there is no repo.
#   3. gh's globally active account -- the fallback when no github.user is set
#      (a personal repo, or any machine with a single-identity gitconfig).

# Computed per call, not once at source time: gh-account.sh moves
# GH_CONFIG_DIR on every cd, so a snapshot taken when the shell started would
# keep pointing at whichever store happened to be active then.
__gh_ps1_hosts() {
    printf '%s' "${GH_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/gh}/hosts.yml"
}

# `${var=}` rather than `var=` so re-sourcing the file keeps the cache warm.
: "${__gh_ps1_key=}"
: "${__gh_ps1_account=}"

# Layer 2. Standing in the work tree but not inside a repo, layer 1 is empty: a
# gitdir: condition is matched against the repo's .git, so with no repo there is
# nothing to match and the include never fires. (Pointing GIT_DIR at a would-be
# path doesn't help -- git only evaluates the condition when the directory
# actually exists.) So apply the gitdir: rules to $PWD here instead.
#
# Only the gitdir: rules, and only on this no-repo path: the hasconfig: ones
# match on a remote URL, which by definition doesn't exist when there is no
# repo, and when there *is* a repo layer 1 has already applied all of them.
__gh_ps1_gitdir_account() {
    # Lines look like: includeif.gitdir:~/work/.path ~/.config/git/work.inc
    git config --global --get-regexp '^includeif\.gitdir:.*\.path$' 2>/dev/null |
    while IFS=' ' read -r key file; do
        local pattern="${key#includeif.gitdir:}"
        pattern="${pattern%.path}"

        local dir
        case "$pattern" in
            '~/'*) dir="$HOME/${pattern#\~/}" ;;
            /*)    dir="$pattern" ;;
            # Bare patterns are implicitly **/-prefixed and the rest can glob
            # mid-path. Guessing at those would risk diverging from git's real
            # matching, and a repo would have resolved them for us anyway.
            *)     continue ;;
        esac
        dir="${dir%/}"

        case "$PWD/" in
            "$dir"/*) git config --file "${file/#\~/$HOME}" --get github.user 2>/dev/null ;;
        esac
    # Every match prints; last one wins, the same precedence git gives includes.
    done | tail -1
}

# Layer 3. `gh auth status` costs ~100ms, far too slow to run per-prompt, so
# read hosts.yml directly: the host block's top-level `user:` is the active
# account (the names nested under `users:` are every account gh knows about,
# active or not). First host wins if several are configured.
__gh_ps1_active_account() {
    local hosts
    hosts=$(__gh_ps1_hosts)
    [ -r "$hosts" ] || return
    # Indentation depth has moved between gh versions, so match on the key
    # rather than a fixed column. `users:` can't collide: the trailing `s`
    # means it never matches `user:`.
    sed -n 's/^[[:space:]]*user:[[:space:]]*//p' "$hosts" | head -1
}

__gh_ps1_resolve() {
    local account
    account=$(git config --get github.user 2>/dev/null)
    [ -n "$account" ] || account=$(__gh_ps1_gitdir_account)
    [ -n "$account" ] || account=$(__gh_ps1_active_account)
    printf '%s' "$account"
}

__gh_ps1() {
    # Resolving costs up to three git forks, which is too much to repeat on
    # every prompt, so cache it and redo the work only when an input moves: the
    # directory, or either config file. One stat covers both files, so a repeat
    # prompt in the same directory costs a single fork. Editing an *included*
    # .inc is not caught -- it needs a new shell or a cd away and back.
    local key
    key="$PWD:$(stat -c %Y "$HOME/.gitconfig" \
                          "${XDG_CONFIG_HOME:-$HOME/.config}/git/config" \
                          "$(__gh_ps1_hosts)" 2>/dev/null)"
    if [ "$key" != "$__gh_ps1_key" ]; then
        __gh_ps1_key="$key"
        __gh_ps1_account=$(__gh_ps1_resolve)
    fi
    printf '%s' "$__gh_ps1_account"
}

# --- routing ----------------------------------------------------------------
# Everything above only *reports* the account. This half makes it true, by
# exporting GH_CONFIG_DIR so the gh process reads that account's credentials.
# The two belong together: without the routing the prompt is a claim rather
# than a fact -- it read the work account out of the git config while gh itself
# still used the personal token, which is the silent wrong-account bug
# IdentitiesOnly exists to prevent on the ssh side.
#
# One account per store, discovered by reading each store's hosts.yml rather
# than from a table here (see ~/.config/gh/ACCOUNTS.md on a given machine):
#
#     ~/.config/gh            the default store
#     ~/.config/gh-<name>     one per additional account
#
# GH_CONFIG_DIR is per-process, so two terminals in different trees never
# fight. `gh auth switch` would rewrite hosts.yml globally and could retarget a
# long-running job from an unrelated directory.

__gh_default_store() { printf '%s' "${XDG_CONFIG_HOME:-$HOME/.config}/gh"; }

# Account -> store, by reading the active `user:` out of each store rather than
# from a hardcoded table: a third account is `gh auth login` into a new
# ~/.config/gh-<whatever>, with no edit here. Same spirit as the includeIf
# rules, which a new internal org also needs nothing beyond.
__gh_store_for_account() {
    [ -n "$1" ] || return 1
    local hosts active
    for hosts in "${XDG_CONFIG_HOME:-$HOME/.config}"/gh*/hosts.yml; do
        [ -r "$hosts" ] || continue
        active=$(sed -n 's/^[[:space:]]*user:[[:space:]]*//p' "$hosts" | head -1)
        if [ "$active" = "$1" ]; then
            printf '%s' "${hosts%/hosts.yml}"
            return 0
        fi
    done
    return 1
}

# Unset for the default store rather than setting it explicitly, so the common
# case leaves a clean environment and behaves like a machine without this file.
__gh_apply_store() {
    if [ "$1" = "$(__gh_default_store)" ]; then
        unset GH_CONFIG_DIR
    else
        export GH_CONFIG_DIR="$1"
    fi
}

__gh_route() {
    [ -n "$GH_ACCOUNT_PIN" ] && return 0   # ghuse override, until the next cd

    # Resolve with GH_CONFIG_DIR cleared. Layer 3 falls back to whichever store
    # it can see, so leaving the previous directory's store in the environment
    # would make the answer depend on where we just came from: cd out of the
    # work tree and layer 3 reads the work store, re-elects the work account,
    # and the account never returns to personal.
    local account store
    account=$(GH_CONFIG_DIR= __gh_ps1_resolve)
    store=$(__gh_store_for_account "$account") || store=$(__gh_default_store)
    __gh_apply_store "$store"
}

# Manual override, cleared by the next cd. Takes an account name, not a path.
ghuse() {
    if [ -z "$1" ]; then
        printf 'usage: ghuse <account>\nknown:\n' >&2
        local hosts
        for hosts in "${XDG_CONFIG_HOME:-$HOME/.config}"/gh*/hosts.yml; do
            [ -r "$hosts" ] || continue
            printf '  %-18s %s\n' \
                "$(sed -n 's/^[[:space:]]*user:[[:space:]]*//p' "$hosts" | head -1)" \
                "${hosts%/hosts.yml}" >&2
        done
        return 2
    fi
    local store
    store=$(__gh_store_for_account "$1") || {
        printf 'ghuse: no store holds account %s\n' "$1" >&2
        return 1
    }
    __gh_apply_store "$store"
    export GH_ACCOUNT_PIN="$1"
}

# Token for the active store, for the occasional script that needs one in an
# env var. Deliberately a command rather than an export in secrets.env: a
# GH_TOKEN in the environment overrides gh's stored credentials for *every*
# account and would defeat the routing above.
ghtoken() {
    local hosts
    hosts="${GH_CONFIG_DIR:-$(__gh_default_store)}/hosts.yml"
    [ -r "$hosts" ] || { printf 'ghtoken: no store at %s\n' "$hosts" >&2; return 1; }
    sed -n 's/^[[:space:]]*oauth_token:[[:space:]]*//p' "$hosts" | head -1
}

# zsh gets a real chpwd hook. bash has none, so PROMPT_COMMAND stands in and
# compares against the last seen directory -- routing on every prompt would
# re-fork git for a bare <enter>. Both prompts source this file already, so
# there is nothing to wire up in .zshrc or rc.sh.
if [ -n "$ZSH_VERSION" ]; then
    autoload -Uz add-zsh-hook
    __gh_chpwd() { unset GH_ACCOUNT_PIN; __gh_route; }
    add-zsh-hook chpwd __gh_chpwd
elif [ -n "$BASH_VERSION" ]; then
    __gh_chpwd() {
        [ "$PWD" = "$__gh_last_pwd" ] && return 0
        __gh_last_pwd="$PWD"
        unset GH_ACCOUNT_PIN
        __gh_route
    }
    # __zfiles_prompt calls __gh_chpwd itself; this file is sourced from the top
    # of bash/prompt.sh, so prepending to PROMPT_COMMAND here would be undone by
    # the assignment at the bottom of that file. Fall back to PROMPT_COMMAND
    # only for a bash that loads git-prompt.sh without the zfiles prompt.
    case "$PROMPT_COMMAND" in
        *__gh_chpwd*) ;;
        '')  PROMPT_COMMAND='__gh_chpwd' ;;
        *)   PROMPT_COMMAND="__gh_chpwd;$PROMPT_COMMAND" ;;
    esac
    __gh_last_pwd="$PWD"
fi

# Route the shell's starting directory: hooks only fire on a later cd, and a
# terminal opened straight into a work tree would otherwise start on the wrong
# store.
__gh_route
