# zsh entry point for the shared environment.
#
# Chain: ~/.zshenv (generated by bootstrap) -> $ZDOTDIR/.zshenv (this file)
#        -> ~/.config/shell/env.sh (shared with bash).
#
# Anything shell-agnostic belongs in env.sh, not here — bash reads that same
# file via ~/.config/bash/rc.sh, and the remote target ships it without zsh.
source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"
