"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
	# Navigation
	{ on = [ "u" ], run = "arrow -1" },
	{ on = [ "e" ], run = "arrow 1" },

	{ on = [ "U" ], run = "arrow -5" },
	{ on = [ "E" ], run = "arrow 5" },

	{ on = [ "h" ], run = [ "leave", "escape --visual --select" ] },
	{ on = [ "l" ], run = [ "plugin --sync enter-or-open", "escape --visual --select" ] },

	{ on = [ "H" ], run = "back" },
	{ on = [ "L" ], run = "forward" },

	{ on = [ "<C-u>" ], run = "seek -5" },
	{ on = [ "<C-e>" ], run = "seek 5" },

	# Operation
	# { on = [ "s" ], run = "link" },
	# { on = [ "S" ], run = "link --relative" },

	# Find
	{ on = [ "-" ], run = "find_arrow" },
	{ on = [ "=" ], run = "find_arrow --previous" },

  { on = [ "y" ], run = [ "yank", '''shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'''' ]},
]

[tasks]

prepend_keymap = [
	{ on = [ "u" ], run = "arrow -1" },
	{ on = [ "e" ], run = "arrow 1" },
]

[select]

prepend_keymap = [
	{ on = [ "u" ], run = "arrow -1" },
	{ on = [ "e" ], run = "arrow 1" },

	{ on = [ "U" ], run = "arrow -5" },
	{ on = [ "E" ], run = "arrow 5" },
]

[input]

prepend_keymap = [
	# Mode
	{ on = [ "k" ],     run = "insert" },
	{ on = [ "<C-n>" ], run = [ "move -999", "insert" ] },
	{ on = [ "<C-i>" ], run = [ "move 999", "insert --append" ] },

	# Character-wise movement
	{ on = [ "n" ], run = "move -1" },
	{ on = [ "i" ], run = "move 1" },

	# Word-wise movement
	{ on = [ "h" ], run = "forward --end-of-word" },

	# Line-wise movement
	{ on = [ "N" ], run = "move -999" },
	{ on = [ "I" ], run = "move 999" },

	# Undo/Redo
	{ on = [ "l" ], run = "undo" },
	{ on = [ "L" ], run = "redo" },

  { on = [ "<Esc>" ], run = "close", desc = "Cancel input"},
]

[completion]

prepend_keymap = [
	{ on = [ "<C-u>" ], run = "arrow -1" },
	{ on = [ "<C-e>" ], run = "arrow 1" },
]

[help]

prepend_keymap = [
	# Navigation
	{ on = [ "u" ], run = "arrow -1" },
	{ on = [ "e" ], run = "arrow 1" },

	{ on = [ "U" ], run = "arrow -5" },
	{ on = [ "E" ], run = "arrow 5" },
]
