# Auto-generated by omarchy-theme-set-templates from this template.
# Source: ~/.config/omarchy/themed/yazi-omarchy-theme.toml.tpl (zfiles)
# Output: ~/.config/omarchy/current/theme/yazi-omarchy-theme.toml
# Yazi reads it as the "omarchy" flavor:
#   ~/.config/yazi/flavors/omarchy.yazi/flavor.toml -> this output
# theme.toml selects it with [flavor] dark = "omarchy".

[manager]
cwd = { fg = "{{ color6 }}" }
hovered = { bg = "{{ selection_background }}", fg = "{{ selection_foreground }}" }
preview_hovered = { bg = "{{ selection_background }}" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "{{ color8 }}" }

mode_normal = { bg = "{{ color4 }}", fg = "{{ background }}", bold = true }
mode_select = { bg = "{{ color2 }}", fg = "{{ background }}", bold = true }
mode_unset = { bg = "{{ color5 }}", fg = "{{ background }}", bold = true }

progress_label = { fg = "{{ foreground }}" }
progress_normal = { fg = "{{ color4 }}" }
progress_error = { fg = "{{ color1 }}" }

permissions_t = { fg = "{{ color2 }}" }
permissions_r = { fg = "{{ color3 }}" }
permissions_w = { fg = "{{ color1 }}" }
permissions_x = { fg = "{{ color6 }}" }
permissions_s = { fg = "{{ color5 }}" }

[select]
border = { fg = "{{ color4 }}" }
active = { fg = "{{ color5 }}", bold = true }
inactive = { fg = "{{ foreground }}" }

[input]
border = { fg = "{{ color4 }}" }
title = { fg = "{{ foreground }}" }
value = { fg = "{{ foreground }}" }
selected = { bg = "{{ selection_background }}" }

[completion]
border = { fg = "{{ color4 }}" }
active = { bg = "{{ selection_background }}" }
inactive = { fg = "{{ color8 }}" }

[tasks]
border = { fg = "{{ color4 }}" }
title = { fg = "{{ foreground }}" }
hovered = { fg = "{{ color5 }}" }

[which]
mask = { bg = "{{ color8 }}" }
cand = { fg = "{{ color6 }}" }
rest = { fg = "{{ color8 }}" }
desc = { fg = "{{ color5 }}" }
separator = " → "
separator_style = { fg = "{{ color8 }}" }

[help]
on = { fg = "{{ color6 }}" }
run = { fg = "{{ color5 }}" }
desc = { fg = "{{ foreground }}" }
hovered = { bg = "{{ selection_background }}", bold = true }
footer = { fg = "{{ color8 }}" }

[notify]
title_info = { fg = "{{ color2 }}" }
title_warn = { fg = "{{ color3 }}" }
title_error = { fg = "{{ color1 }}" }

[filetype]
rules = [
    { url = "*", fg = "{{ foreground }}" },
    { url = "*/", fg = "{{ color4 }}" },
]
