
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output\\.pci-.*1f\\.3.*analog-stereo" }
    ]
    actions = {
      update-props = {
        priority.session = 2000
        priority.driver = 2000
      }
    }
  }
  {
    matches = [
      { node.name = "~.*\\.hdmi-stereo.*" }
    ]
    actions = {
      update-props = {
        priority.session = 100
        priority.driver = 100
      }
    }
  }
]
